ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: wiki.vmtlw.ru
      paths:
        - path: "/"
          pathType: Prefix

  tls:
    - secretName: tls
      hosts:
        - wiki.vmtlw.ru


