apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  metadata:
  name: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.1.1
    helm:
      releaseName: argo-cd
      valueFiles:
        - values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
