apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  metadata:
  name: wikijs
  finalizers:
    - resources-finalizer.argocd.argoproj.io/resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.js.wiki
    chart: wiki
    targetRevision: 2.2.23
    helm:
      releaseName: wikijs
      valueFiles:
        - name: values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: wikijs
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
