apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  metadata:
  namespace: argocd
  name: wikijs
spec:
  project: default
  source:
    repoURL: https://charts.js.wiki
    chart: wiki
    targetRevision: 2.2.23
    path: clusters/vmtlw/infrastructure/apps/wikijs
    helm:
      releaseName: wikijs
      valueFiles:
        - values.yml
      chart: .
  destination:
    server: https://kubernetes.default.svc
    namespace: wikijs
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
