apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-synapse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ananace.gitlab.io/charts
    chart: matrix-synapse
    targetRevision: 3.12.3
    helm:
      releaseName: matrix-synapse
      valuesFiles:
        - values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: matrix-synapse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
