apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.18.1
    helm:
      releaseName: cert-manager
      valuesFiles:
        - values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
