apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: 
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 9.2.7
    helm:
      releaseName: grafana
      valuesFiles:
        - values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
