---
name: Validate YAML

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: Run yamllint
        run: yamllint .

